# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dscp" #Must be unique in Heroku
          heroku_email: "ali.ohhb@gmail.com"
          remote_branch: "main"
      env:
        HD_DbUri: ${{secrets.DbUri}}
        HD_DbName: ${{secrets.DbName}}
        HD_MFS: ${{secrets.MFS}}
        HD_MRS: ${{secrets.MRS}}
        HD_jwtExpirationInMs: ${{secrets.jwtExpirationInMs}}
        HD_jwtSecret: ${{secrets.jwtSecret}}
        HD_refreshTokenExpirationInMs: ${{secrets.refreshTokenExpirationInMs}}
        HD_refreshTokenSecret: ${{secrets.refreshTokenSecret}}    
    env:
      DbUri: ${{secrets.DbUri}}
      DbName: ${{secrets.DbName}}
      MFS: ${{secrets.MFS}}
      MRS: ${{secrets.MRS}}
      jwtExpirationInMs: ${{secrets.jwtExpirationInMs}}
      jwtSecret: ${{secrets.jwtSecret}}
      refreshTokenExpirationInMs: ${{secrets.refreshTokenExpirationInMs}}
      refreshTokenSecret: ${{secrets.refreshTokenSecret}}

